-- agent_messages PK: id → (owner_id, id).
-- `id` is a CLIENT nonce, unique only within one pod's outbox. Keying the PK on `id` alone let the
-- SAME nonce generated by two DIFFERENT owners collide, so the second owner's message was silently
-- dropped by the drain's ON CONFLICT DO NOTHING. Scoping the PK to (owner_id, id) keeps re-drain
-- idempotent PER OWNER while making cross-owner nonce reuse two distinct messages.
-- Existing rows have globally-unique ids, so the composite is trivially unique — no data conflict.
ALTER TABLE "agent_messages" DROP CONSTRAINT "agent_messages_pkey";--> statement-breakpoint
ALTER TABLE "agent_messages" ADD CONSTRAINT "agent_messages_pkey" PRIMARY KEY ("owner_id","id");
